/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/brain.glb --output src/components/Brain.jsx 
Author: dgallichan (https://sketchfab.com/dgallichan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-cadd2bde67404c43b2359a6a3281d84a
Title: Brain
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Brain(props) {
  const { nodes } = useGLTF('/brain.glb');

  const baseColor = "#f2aeb1";

  return (
    <group {...props} scale={[0.15, 0.15, 0.15]} dispose={null} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
      {Object.values(nodes).map((node) => {
        if (node.isMesh) {
          return (
            <mesh key={node.uuid} geometry={node.geometry}>
              <meshStandardMaterial color={baseColor} roughness={0.3} metalness={0.5} />
            </mesh>
          );
        }
        return null;
      })}
    </group>
  );
}

useGLTF.preload('/brain.glb')
